### ISSUE TITLE
using locale for t function

### ISSUE THREAD

**Issue by tuevo21** [airbnb/polyglot.js#65]
Do you think it helps to get different output from t with specified locale?

For example:

polyglot.extend("hello", {locale:"fr", text:"bonjour"});
polyglot.extend("hello", {locale:"it", text:"ciao"}); 
polyglot.t("hello", {locale:"fr"}); //bonjour
polyglot.t("hello", {locale:"it"}); //ciao

**Comment by ljharb** [comment]
The idea with polyglot is that you `.extend` with only the phrases for a single locale, and if you need to change locales, you either use a different polyglot instance, or you `.clear` and then `.extend` with the new locale.

You can achieve this now with a map of locale to polyglot instance, for example, so that you'd do `map.fr.t('hello') === 'bonjour' && map.it.t('hello') === 'ciao'`
